In [1]:
#from mpl_toolkits import mplot3d
import array
import pandas
import matplotlib
import math   # 导入 math 模块
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from pandas import Series, DataFrame
from sklearn.model_selection import train_test_split
from IPython.core.pylabtools import figsize
from sklearn.model_selection import cross_val_score
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from scipy import stats
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold
from scipy.stats import pearsonr,spearmanr
from itertools import combinations
from scipy.special import comb, perm
from sklearn.kernel_ridge import KernelRidge
from sklearn.model_selection import ShuffleSplit
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

rs_1 = ShuffleSplit(n_splits=10, test_size=.85, random_state=0)
rs_2 = ShuffleSplit(n_splits=10, test_size=.80, random_state=0)
rs_3 = ShuffleSplit(n_splits=10, test_size=.75, random_state=0)
rs_4 = ShuffleSplit(n_splits=10, test_size=.70, random_state=0)
rs_5 = ShuffleSplit(n_splits=10, test_size=.65, random_state=0)
rs_6 = ShuffleSplit(n_splits=10, test_size=.60, random_state=0)
rs_7 = ShuffleSplit(n_splits=10, test_size=.55, random_state=0)
rs_8 = ShuffleSplit(n_splits=10, test_size=.50, random_state=0)
rs_9 = ShuffleSplit(n_splits=10, test_size=.45, random_state=0)
rs_10 = ShuffleSplit(n_splits=10, test_size=.40, random_state=0)
rs_11 = ShuffleSplit(n_splits=10, test_size=.35, random_state=0)
rs_12 = ShuffleSplit(n_splits=10, test_size=.30, random_state=0)
rs_13 = ShuffleSplit(n_splits=10, test_size=.25, random_state=0)
rs_14 = ShuffleSplit(n_splits=10, test_size=.20, random_state=0)
rs_15 = ShuffleSplit(n_splits=10, test_size=.15, random_state=0)

scaler_M = MinMaxScaler()

data_train=pandas.read_csv(r"C:\Users\z\Desktop\图表及相应源代码\Fig 4\F_train.csv")
data_test=pandas.read_csv(r"C:\Users\z\Desktop\图表及相应源代码\Fig 4\F_test.csv")

sf_train=np.array(data_train.sf)/100
Vsv_train=np.array(data_train.sv_Volume)
Vso_train=np.array(data_train.so_Volume)
N_sv_train=np.array(data_train.N_sv)
N_so_train=np.array(data_train.N_so)

sf_test=np.array(data_test.sf)/100
Vsv_test=np.array(data_test.sv_Volume)
Vso_test=np.array(data_test.so_Volume)
N_sv_test=np.array(data_test.N_sv)
N_so_test=np.array(data_test.N_so)

In [2]:
F_train=np.array(data_train)
p_train=data_train.ev_ratio
p_train=np.array(p_train)
F_0train=F_train[:,3:67]

F_test=np.array(data_test)
p_test=data_test.ev_ratio
p_test=np.array(p_test)
F_0test=F_test[:,3:67]

F_0train.shape

(368, 64)

In [3]:
#注意输入rs
n=8
tr=[]
te=[]

for train_index, test_index in rs_1.split(F_0train):
    tr.append(train_index)
    te.append(test_index)

In [6]:
tr[8]

array([175, 223, 356, 302,  74, 161, 162, 350, 110,  71, 199, 201, 328,
        54, 155, 111, 145,  46, 274,   3, 267, 246, 284, 169, 358,   7,
       181,  73, 197, 189, 193,  39, 100,  57,  63, 348, 232, 174, 165,
       239, 213,   0, 183, 211,  37, 341, 312, 296, 135, 212, 210, 322,
       179,  13, 120])

In [7]:
tr=[]
te=[]

for train_index, test_index in rs_2.split(F_0train):
    tr.append(train_index)
    te.append(test_index)

In [8]:
tr[8]

array([131, 137, 251,  91, 156, 195, 359, 124, 291,  35,   5, 150, 321,
       355, 301, 119, 191, 104, 175, 223, 356, 302,  74, 161, 162, 350,
       110,  71, 199, 201, 328,  54, 155, 111, 145,  46, 274,   3, 267,
       246, 284, 169, 358,   7, 181,  73, 197, 189, 193,  39, 100,  57,
        63, 348, 232, 174, 165, 239, 213,   0, 183, 211,  37, 341, 312,
       296, 135, 212, 210, 322, 179,  13, 120])

In [10]:
tr=[]
te=[]

for train_index, test_index in rs_3.split(F_0train):
    tr.append(train_index)
    te.append(test_index)

In [11]:
tr[8]

array([ 97, 159, 188, 332, 309, 353,  41, 184,  79, 329, 204,  47,  69,
         2, 157, 132, 234, 106, 107, 131, 137, 251,  91, 156, 195, 359,
       124, 291,  35,   5, 150, 321, 355, 301, 119, 191, 104, 175, 223,
       356, 302,  74, 161, 162, 350, 110,  71, 199, 201, 328,  54, 155,
       111, 145,  46, 274,   3, 267, 246, 284, 169, 358,   7, 181,  73,
       197, 189, 193,  39, 100,  57,  63, 348, 232, 174, 165, 239, 213,
         0, 183, 211,  37, 341, 312, 296, 135, 212, 210, 322, 179,  13,
       120])

In [5]:
#'rbf''laplacian'
n_alphas = 100
alphas = np.logspace(-6, 0.6, n_alphas)

kr=GridSearchCV(KernelRidge(kernel='laplacian'), cv=10,
                 param_grid={"alpha": alphas,
                            "gamma": np.logspace(-10, 2, 50)})

In [6]:
scaler_M.fit(F_0train[tr[n],:])
F_tr=scaler_M.transform(F_0train[tr[n],:])
    
resul= kr.fit(F_tr,(p_train.reshape(-1,1)[tr[n],:]-1)*100)
    
_alpha=resul.best_params_.pop('alpha')
_gamma=resul.best_params_.pop('gamma')

krr=KernelRidge(alpha=_alpha, 
                #kernel='rbf',
                kernel='laplacian',
                gamma=_gamma)

In [7]:
F_test=scaler_M.transform(F_0test)

krr.fit(F_tr,(p_train.reshape(-1,1)[tr[n],:]-1)*100)
    
p_tr = krr.predict(F_tr)
r_2_tr=r2_score((p_train.reshape(-1,1)[tr[n],:]-1)*100, p_tr)
    
p_pre = krr.predict(F_test)   
r_2=r2_score((p_test.reshape(-1,1)-1)*100, p_pre)

print(r_2_tr)
print(r_2)

0.9999999999982951
0.618343957035649


In [8]:
ind=[]
r2=[]

In [9]:
sub=63
for l in range(0,sub):
    
    evaluate_r_2=[]
    evaluate_r_2_tr=[]
    
    for k in range(0,np.shape(F_0train)[1]):
        
        F_d=np.delete(F_0train,k,1)
        F_dtest=np.delete(F_0test,k,1)
            
        scaler_M.fit(F_d) 
        
        F_tr=scaler_M.transform(F_d[tr[n],:])
        F_te=scaler_M.transform(F_dtest)
        
        krr.fit(F_tr,(p_train.reshape(-1,1)[tr[n],:]-1)*100)
            
        p_tr = krr.predict(F_tr)
        r_2_tr=r2_score((p_train.reshape(-1,1)[tr[n],:]-1)*100, p_tr)
        evaluate_r_2_tr.append(r_2_tr)
    
        p_pre = krr.predict(F_te)   
        r_2=r2_score((p_test.reshape(-1,1)-1)*100, p_pre)
        evaluate_r_2.append(r_2)
        
    r2.append(max(evaluate_r_2))    
    t=evaluate_r_2.index(max(evaluate_r_2))
    ind.append(t)
    
    F_0train=np.delete(F_0train,t,1)
    F_0test=np.delete(F_0test,t,1)

In [10]:
F_tr.shape

(312, 1)

In [11]:
#removing index
r=pd.DataFrame(ind)
r.to_csv('index_training_size0.85.csv')
#testing accuracy
r=pd.DataFrame(r2)
r.to_csv('r2_training_size0.85.csv')